name: Continuous integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install libssl-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          components: rustfmt, clippy

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: latest
          use-tool-cache: true

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Check kvm-core module
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path kvm-core/Cargo.toml

      - name: Test kvm-core module
        run: cd kvm-core && wasm-pack test --node

      - name: Check kvm-core code formatting
        id: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path kvm-core/Cargo.toml --all -- --check

      - name: Check kvm-core module for linter warnings
        id: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path kvm-core/Cargo.toml -- -D warnings

      - name: Cache Cargo build artefacts
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.head_ref }}-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.head_ref }}
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo

      - name: Install Node dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build project
        run: yarn run pack
